data_dir: /kaggle/input/competitions/rogii-wellbore-geology-prediction
output_dir: /kaggle/working
model_dir: /kaggle/working/models
# Pre-trained model from rogii-models Kaggle Dataset (produced by 01_kaggle_train.ipynb)
model_input: /kaggle/input/datasets/daniilgonchar/rogii-models/baseline_lgbm.pkl
submission_dir: /kaggle/working
mlflow_tracking_uri: /kaggle/working/mlruns
